{{ if .Values.plugins.rotten.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name | default .Chart.Name }}-close-rotten
spec:
  schedule: "0 18 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: {{ .Values.name | default .Chart.Name }}
        spec:
          containers:
          - name: close-rotten
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: GITLAB_BASE_URL
              value: {{ .Values.gitlab.url }}
            - name: GITLAB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gitlab.secret }}
                  key: token
            - name: REQUESTS_CA_BUNDLE
              value: /etc/ssl/certs/ca-certificates.crt
            - name: CLOSE_AFTER
              value: "{{ .Values.plugins.rotten.close_after }}"
            - name: ROTTEN_LABEL
              value: {{ .Values.plugins.rotten.label }}
            - name: PROJECTS
              value: {{ .Values.projects | join "," }}
            command: ["/jobs/close-rotten.py"]
          restartPolicy: Never
{{ end }}