apiVersion: batch/v1
kind: CronJob
metadata:
  name: mark-rotten
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mark-rotten
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: GITLAB_BASE_URL
              value: {{ .Values.gitlab.url }}
            - name: GITLAB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gitlab.secret }}
                  key: token
            - name: ROTTEN_AFTER
              value: "{{ .Values.plugins.rotten.mark_after }}"
            - name: ROTTEN_LABEL
              value: {{ .Values.plugins.rotten.label }}
            - name: PROJECTS
              value: {{ .Values.projects | join "," }}
            command: ["/jobs/mark-rotten.py"]
          restartPolicy: Never